# Generated by Django 4.2.5 on 2023-10-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyapp', '0002_shopifyblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopifyapp.shopifyblog')),
            ],
        ),
    ]
